# Generated by Django 3.1.4 on 2020-12-06 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BTCAddresses',
            fields=[
                ('address', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('isUsed', models.BooleanField(default=False)),
                ('user_id', models.IntegerField(blank=True, default=None, null=True)),
                ('label', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
    ]
